kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zcashd-data-claim
  namespace: testnet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zcashd-param-claim
  namespace: testnet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
 