kind: PersistentVolume
apiVersion: v1
metadata:
  name: zcash-peer-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/zcash-peer/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zcash-peer-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zcash-peer-params-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/zcash-peer/params"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zcash-peer-params
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
---
apiVersion: v1
kind: Service
metadata:
  name: zcashd-peer
  labels:
    app: zcashd-peer
spec:
  ports:
    - name: zcashd-rpc
      port: 18232
      targetPort: 18232
    - name: zcashd-zmq1
      port: 28332
      targetPort: 28332
    - name: zcashd-zmq2
      port: 9994
      targetPort: 9994
  selector:
    app: zcashd
    version: v2.0.6
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zcashd-peer
  labels:
    app: zcashd-peer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zcashd-peer
      version: v2.0.6
      tier: backend
  template:
    metadata:
      labels:
        app: zcashd-peer
        version: v2.0.6
        tier: backend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers: 
        - name: zcashd-peer
          image: alphegasolutions/zcashd:v2.0.6
          imagePullPolicy: Never
          env:
            - name: ZCASH_HOME
              value: /home/zcash
            - name: ZCASH_CONF
              value: /home/zcash/.zcash/zcash.conf
            - name: ZCASH_NETWORK
              value: testnet
            - name: ZCASH_RPC_PORT
              value: "18232"
            - name: ZCASH_ZMQ1_PORT
              value: "9994"
            - name: ZCASH_ZMQ2_PORT
              value: "28332"
            - name: ZCASH_NODE_TYPE
              value: "node"
            - name: ZCASH_USER
              value: zcash
            - name: ZCASH_PASS
              value: password
            - name: ZCASH_RPC_USER
              value: zcash
            - name: ZCASH_RPC_PASS
              value: password
            - name: ZCASH_SERVICE
              value: zcashd
          ports:
            - name: zcashd-rpc
              containerPort: 18232
              protocol: TCP
            - name: zcashd-zmq1
              containerPort: 28332
              protocol: TCP
            - name: zcashd-zmq2
              containerPort: 9994
              protocol: TCP
          volumeMounts:
            - name: zcash-peer-data
              mountPath: /home/zcash/.zcash
            - name: zcash-peer-params
              mountPath: /home/zcash/.zcash-params
          securityContext:
            allowPrivilegeEscalation: false
            
      volumes:
        - name: zcash-peer-data
          persistentVolumeClaim:
            claimName: zcash-peer-data
        - name: zcash-peer-params
          persistentVolumeClaim:
            claimName: zcash-peer-params
