kind: PersistentVolume
apiVersion: v1
metadata:
  name: zcash-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: "/tmp/zcash/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zcash-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zcash-params-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/zcash/params"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zcash-params
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
---
apiVersion: v1
kind: Service
metadata:
  name: zcashd
  labels:
    app: zcashd
spec:
  ports:
    - name: zcashd-rpc
      port: 18232
      targetPort: 18232
    - name: zcashd-zmq
      port: 28332
      targetPort: 28332
    - name: zcashd-1
      port: 9994
      targetPort: 9994
  selector:
    app: zcashd
    version: v2.0.6
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zcashd
  labels:
    app: zcashd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zcashd
      version: v2.0.6
      tier: backend
  template:
    metadata:
      labels:
        app: zcashd
        version: v2.0.6
        tier: backend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers: 
        - name: zcashd
          image: alphegasolutions/zcashd:v2.0.6
          imagePullPolicy: Never
          env:
            - name: ZCASH_HOME
              value: /home/zcash
            - name: ZCASH_CONF
              value: /home/zcash/.zcash/zcash.conf
            - name: ZCASH_NETWORK
              value: testnet
            - name: ZCASH_NODE_TYPE
              value: node
            - name: ZCASH_USER
              value: zcash
            - name: ZCASH_PASS
              value: password
            - name: ZCASH_RPC_USER
              value: zcash
            - name: ZCASH_RPC_PASS
              value: password
            - name: ZCASH_NODE_TYPE
              value: PEER
          ports:
            - name: zcashd-rpc
              containerPort: 18232
              protocol: TCP
            - name: zcashd-zmq
              containerPort: 28332
              protocol: TCP
            - name: zcashd-l
              containerPort: 9994
              protocol: TCP
          volumeMounts:
            - name: zcash-data
              mountPath: /home/zcash/.zcash
            - name: zcash-params
              mountPath: /home/zcash/.zcash-params
#            - name: zcashd-conf
#              mountPath: /etc/zcash/conf
          securityContext:
            allowPrivilegeEscalation: false
#      initContainers:
#        - name: config-data
#          image: busybox
#          env:
#            - name: ZCASH_HOME
#              value: /home/zcash
#            - name: ZCASH_CONF
#              value: /home/zcash/.zcash/zcash.conf
#            - name: ZCASH_NETWORK
#              value: testnet
#            - name: ZCASH_NODE_TYPE
#              value: NODE
#          command:
#            - echo
#            - -n
#            - testnet=1 
#            - >
#            - ${ZCASH_CONF}
#            - "echo server=1" >> ${ZCASH_CONF}
#            - "echo whitelist=0.0.0.0" >> ${ZCASH_CONF}
#            - "echo rpcallowip=0.0.0.0" >> ${ZCASH_CONF}
#            - "echo rpcuser=zcash" >> ${ZCASH_CONF}
#            - "echo rpcpassword=zcash123" >> ${ZCASH_CONF}
#            - "echo addnode=testnet.z.cash" >> ${ZCASH_CONF}
#            - "echo zmqpubrawtx=tcp://0.0.0.0:9994" >> ${ZCASH_CONF}
#            - "echo zmqpubhashblock=tcp://0.0.0.0:9994" >> ${ZCASH_CONF}
#            - "echo zmqpubcheckedblock=tcp://0.0.0.0:28332" >> ${ZCASH_CONF}
#            - "echo reindex=1" >> ${ZCASH_CONF}
#            - "echo showmetrics=0" >> ${ZCASH_CONF}
#            - "echo txindex=1" >> ${ZCASH_CONF}
#            - "echo addressindex=1" >> ${ZCASH_CONF}
#            - "echo timestampindex=1" >> ${ZCASH_CONF}
#            - "echo spentindex=1" >> ${ZCASH_CONF}
            
      volumes:
        - name: zcash-data
          persistentVolumeClaim:
            claimName: zcash-data
#          hostPath:
#            path: /tmp/zcash-data
#            type: Directory
        - name: zcash-params
          persistentVolumeClaim:
            claimName: zcash-params
#          hostPath:
#            path: /tmp/zcash-params
#            type: Directory 
