kind: PersistentVolume
apiVersion: v1
metadata:
  name: zcash-ui-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/zcash-ui/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zcash-ui-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zcash-ui-params-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/zcash-ui/params"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zcash-ui-params
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
---
apiVersion: v1
kind: Service
metadata:
  name: zcash-ui
#  namespace: testnet
  labels:
    app: zcash-explorer
spec:
  ports:
    - name: zcash-ui
      nodePort: 30957
      port: 3001
      targetPort: 3001
  selector:
    app: zcash-ui
    version: v0.1
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zcash-ui
#  namespace: testnet
  labels:
    app: zcash-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zcash-ui
      version: v0.1
      tier: frontend
  template:
    metadata:
      labels:
        app: zcash-ui
        version: v0.1
        tier: frontend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: zcash-ui
          image: alphegasolutions/zcash-ui:v0.1
          imagePullPolicy: Never
          env:
            - name: ZCASH_HOME
              value: /home/zcash
            - name: ZCASH_NETWORK
              value: testnet
            - name: ZCASH_SERVICE
              value: zcashd
            - name: ZCASH_RPC_PORT
              value: "18232"
            - name: ZCASH_RPC_USER
              value: zcash
            - name: ZCASH_RPC_PASS
              value: password
            - name: ZMQ_BLK_PORT
              value: "9994"
            - name: ZMQ_LWD_PORT
              value: "28332"
          ports:
            - name: zcash-ui-port
              containerPort: 3001
              protocol: TCP
          volumeMounts:
            - name: zcash-ui-data
              mountPath: /home/zcash/.zcash
            - name: zcash-ui-params
              mountPath: /home/zcash/.zcash-params
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: zcash-ui-data
          persistentVolumeClaim:
            claimName: zcash-ui-data
        - name: zcash-ui-params
          persistentVolumeClaim:
            claimName: zcash-ui-params
